dist: xenial # required for Python >= 3.7

language: python

python:
  - "3.7"
  - "3.8"
  - "3.9"

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: pip install -r requirements.txt
script: ./scripts/test && codecov && codecov --token=$CODECOV_TOKEN
