site_name: Dataclasses Avro Schema
site_description: avro, kafka, client, avro schema, apache, python

theme:
  name: 'material'
  palette:
  - scheme: default
    primary: blue grey
    accent: indigo
    toggle:
      icon: material/lightbulb
      name: Switch to dark mode
  - scheme: slate
    primary: blue grey
    accent: indigo
    toggle:
      icon: material/lightbulb-outline
      name: Switch to light mode
  features:
  - search.suggest
  - search.highlight
  - content.tabs.link
  - content.code.annotate

repo_name: marcosschroh/dataclasses-avroschema
repo_url: https://github.com/marcosschroh/dataclasses-avroschema

nav:
  - Introduction: 'index.md'
  - Avro Schema and Python Classes: 'avro_schema.md'
  - Fields Specification: 'fields_specification.md'
  - Primitive Types: 'primitive_types.md'
  - Complex Types: 'complex_types.md'
  - Logical Types: 'logical_types.md'
  - Records: 'records.md'
  - Schema Relationships: 'schema_relationships.md'
  - Serialization: 'serialization.md'
  - Case Schemas: 'case.md'
  - Factory and fixtures: 'factories_and_fixtures.md'
  - Model Generator: 'model_generator.md'
  - Pydantic V1: 'pydantic_v1.md'
  - Pydantic: 'pydantic.md'
  - Faust: 'faust_records.md'
  - Examples: 'examples.md'
  - Good Practices: good_practices.md
  - Migration Guide: 'migration_guide.md'

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.snippets
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.details
  - tables
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.tabbed:
      alternate_style: true 

plugins:
  - autorefs
  - mkdocstrings