name: Tests

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["*"]
  workflow_dispatch:
    inputs:
      release:
        description: 'Release package'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.7', '3.8', '3.9', '3.10', '3.11']
    steps:
    - uses: actions/checkout@v3
    - name: Setup python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        architecture: x64

    - name: Set Cache
      uses: actions/cache@v3
      id: cache  # name for referring later
      with:
        path: /opt/hostedtoolcache/Python/
        key: ${{ matrix.python-version }}-cache-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ matrix.python-version }}-cache-
          ${{ matrix.python-version }}-

    - name: Install Dependencies
      run: |
        pip install -r requirements.txt

    - name: Test
      run: |
        ./scripts/test && codecov && codecov --token=$CODECOV_TOKEN
