name: Tests

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["*"]
  workflow_dispatch:
    inputs:
      release:
        description: "Release package"
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]
    steps:
      - uses: actions/checkout@v4
      - name: Setup python
        uses: actions/setup-python@v5
        with:
          cache: "pip"
          python-version: ${{ matrix.python-version }}
          architecture: x64

      - name: Install Dependencies
        run: |
          python -m pip install -U pip poetry
          poetry --version
          poetry config --local virtualenvs.in-project true
          poetry install --extras "pydantic faust faker"

      - name: Test
        run: ./scripts/test

      - uses: codecov/codecov-action@v3
